DancingOnTheTube/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^listings/', include('listings.urls')),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

listings/urls.py
from django.conf.urls import patterns, url

from listings import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^map/$', views.map, name='map'),
)

listings/models.py
from django.db import models


class Dance(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


class Organization(models.Model):
    name = models.CharField(max_length=200)
    dances = models.ManyToManyField(Dance)

    def __unicode__(self):
        return self.name


class Event(models.Model):
    organization = models.ForeignKey(Organization)
    start_time = models.TimeField()

    def __unicode__(self):
        return self.organization.name


class Repeat(models.Model):
    event = models.OneToOneField(Event, primary_key=True)

    NONE = 'NONE'
    MONTHLY = 'MONTHLY'
    WEEKLY = 'WEEKLY'

    REPEAT = (
        (NONE, 'None'),
        (MONTHLY, 'Monthly'),
        (WEEKLY, 'Weekly')
    )

    frequency = models.CharField(max_length=10, choices=REPEAT, default=NONE)
    nth_day = models.IntegerField(null=True, blank=True)
    n_weeks = models.IntegerField(null=True, blank=True)

    monday = models.BooleanField()
    tuesday = models.BooleanField()
    wednesday = models.BooleanField()
    thursday = models.BooleanField()
    friday = models.BooleanField()
    saturday = models.BooleanField()
    sunday = models.BooleanField()

listings/views.py
from django.shortcuts import render
from listings.models import Dance


def index(request):
    dances = Dance.objects.order_by('name')

    context = {'dances': dances}
    return render(request, 'listings/index.html', context)

def map(request):
    return render(request, 'listings/map.html')

templates/listings/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Dancing on the Tube</title>
</head>
<body>
    <h1>Dance styles</h1>
    {% if dances %}
        {% for dance in dances %}
            <h2>{{ dance.name }}</h2>
            {% for org in dance.organization_set.all %}
                <h3>{{ org.name }}</h3>
            {% endfor %}
        {% endfor %}
    {% else %}
        <p>No dance styles are available.</p>
    {% endif %}
</body>
</html>

templates/listings/map.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map-canvas { height: 100% }
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSik21bT3cscI3jBUxAOI2DTS58qXQi-o&sensor=false">
    </script>
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(51.518411,-0.115013),
          zoom: 10,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);

        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>
  <body>
    <div id="map-canvas" style="height: 80%; width: 80%"/>
  </body>
</html>